name = "Blogpaper-SoyFlavored"
license = "MIT"
licenselink = "https://github.com/Paranoid-AF/Blogpaper-SoyFlavored/blob/master/LICENSE.md"
description = "A graphical newspaper like blog theme for Hugo."
homepage = "https://github.com/Paranoid-AF/Blogpaper-SoyFlavored"
tags = [
  "theme",
  "hugo",
  "blog",
  "minimalist",
  "graphical"
]
features = [
  "minimalist",
  "graphical"
]
min_version = 0.48

[author]
name = "Paranoid_AF"
homepage = "https://soydev.me"

[original]
name = "Erwan Normand"
homepage = "https://normanderwan.fr"
repo = "https://github.com/NormandErwan/Blogpaper"
